### PR TITLE
Added SoftArchive Movies&TV

### PR DESCRIPTION
**Pull request by mastercho**

### CODE REVIEW

**Comment by Purfview** [comment]
It's placed not in alphabetical order, please move it so it's in alphabetical order.

**Comment by mastercho** [comment]
How is now?

**Comment by Purfview** [comment]
> How is now?

Looks in place now. But icons are missing from script, here are steps how to make suitable 200 - 800 bytes icon.

0) Search a web page source code for "icon" to find icons or it's as somesite.com/favicon.ico
1) If there is no png icon then convert it to png. IrfanView or https://cloudconvert.com/ico-to-png
2) Reduce png dimensions to 48x48 or 64x64, reduce colors to 2 - 8 ("Save for Web" in Photoshop). 
3) Remove meta and compress png: https://tinypng.com
4) Get base64 code from png file: https://onlinepngtools.com/convert-png-to-base64

Note: "icon to png" and changing dimensions breaks transparency, transparency needs tweaking with Photoshop. or just make them without transparency if you don't know how to do it.

**Comment by Purfview** [comment]
You didn't used https://tinypng.com ?
Because it reduced your images up to -85% -> https://github.com/Purfview/IMDb-Scout-Mod/commit/1b375d15e788c3bff497eb2ec33e2aff0a6c7ae6

**Comment by Audionut** [comment]
I ran into the transparency problem myself with resizing icons and saving png. It can be done with irfanview.
https://irfanview-forum.de/forum/program/support/10881-

**Pull request merged**
