### PR TITLE
Added few free sites starting with A

### PR DESCRIPTION
**Pull request by mastercho**
I did ditch my experimental commits and pulled fresh 17.0.4 and from now on will start contribute with pull requests

### CODE REVIEW

**Comment by Purfview** [comment]
There are few issues:

1) "AveTorrents" is not a public site, and it's added already.

2) Add loggedOutRegex "Cloudflare|Ray ID" to all sites.

3) Sites should be sequenced alphabetically by the name.

4) "0dayhome" returns something on anything, so it's useless.

5) "AXEL torrents" looks like it's dead, does it work for you?


Reconsider adding DLL sites, there all 9000 of them, most of them  doesn't offer anything unique.
Why not use few best of them like https://rlsbb.cc , it has proper search by IMDb ID, and there are dozens of various download links [in comments too].

**Comment by mastercho** [comment]
1. Used AveTorrents since years and thanks to you i noticed its invites only now... 2 months ago checked and was free signups even in members area there no invites option, so can't invite either....

2. Why is necessary for websites which doesn't have Cloudflare?

3. Do you have easy way to sort them? 

4. Seems now when no result found is empty, have to change keyword

5.Just checked with VPN and seems works only for Bulgarian IP, will add (BG) suffix

I do use rlsbb also but there rare cases which can find movie in other DDL and not in big ones or links dead on big ones

**Comment by Purfview** [comment]
2. If they don't have it now they can have it tomorrow.

3. Don't you know alphabet? Then open some wiki with alphabet as reference.

**Comment by mastercho** [comment]
Did what you asked for

**Comment by Purfview** [comment]
"0dayhome" still returns something on anything, and still not sorted properly.

I'll correct it later.

**Comment by Purfview** [comment]
apps4all doesn't work, so I removed it.
Btw, ATorrents is pointless as it returns result on every word.

**Pull request merged**
