### PR TITLE
Added new sites and fixed clones

### PR DESCRIPTION
**Pull request by mastercho**
Had time to add some new sites,fix clones and even add some clones who are totally different only looks same.

### CODE REVIEW

**Comment by Purfview** [comment]
Just add one site/edit per PR, this PR can't be merged.

**Comment by Purfview** [comment]
Btw, Zelka is the real "zamunda" as Zamunda site was stolen.

**Comment by Purfview** [comment]
If you don't like "zelka" you can use www.zamunda.se which is mirror of zelka aka real zamunda. :)

**Comment by mastercho** [comment]
> Btw, Zelka is the real "zamunda" as Zamunda.net site was stolen.

Well thats was the news but after i get in hands both sites Database and Source code, i see Zelka did this lie to attract users to their site, also they put fake seeders in code. I see you are familiar with Bulgarian sites and you don't like contributions to project

**Comment by Purfview** [comment]
> Well thats was the news but after i get in hands both sites Database and Source code, i see Zelka did this lie to attract users to their site, 

There is an English word for that - bullshit.

> also they put fake seeders in code

You have no clue what you are talking about.

> you don't like contributions to project

It's more that you don't know how to make PRs, you PR is unmergeable because you mixed in different versions of the master in the the one PR.

**Comment by Purfview** [comment]
I just looked at your commits, there are lots shitsites added, we don't want to have here every shitsite on the planet, shitsites are not useful at all in any way. 

I'll review your commits and add useful sites, if you have any other sites to add then you are welcome to do a one site per PR, that means every site should be in the separate PRs.

**Comment by Purfview** [comment]
https://github.com/Purfview/IMDb-Scout-Mod/commit/4b39aa9a3ceb2b2088a9037225ebccd34e74c7c3

Not added:
babytorrent - shitsite
Badass Torrents - subpar aggregator
apps4all - another crappy ddl site
Dllspot - shitty search, another crappy ddl site
Byte - shitty search, another crappy ddl site

Added:
DDLValley, Derinport, Zamunda-stolen, Energy Torrent (BG), Dl4All.org replaced Dl4All

**Pull request closed without merging**
