### PR TITLE
Add DDL-Warez.to (German site)

### PR DESCRIPTION
**Pull request by dimqua**

### CODE REVIEW

**Comment by dimqua** [comment]
No more commits from me for today. :-)

**Comment by Purfview** [comment]
Is this site working? It's not on my side since addition.

**Comment by dimqua** [comment]
Yes, but I can't access it without a German proxy/VPN. They probably only allow German-speaking countries.

**Comment by Purfview** [comment]
Netherlands IP worked too. Moved icon to Imgur. https://github.com/Purfview/IMDb-Scout-Mod/commit/19865ff7dd4709ff64dc751db8ee94687545ad4a

**Pull request merged**
