### PR TITLE
Fixed Favicons: DonTor, ilCorSaRoNeRo, NNM, G-Free, TCTG / Updated URLs: DonTor, NNM, TCTG / Removed Sites: baconBits

### PR DESCRIPTION
**Pull request by neoOpus**
Fixed Favicons: DonTor, ilCorSaRoNeRo, NNM, G-Free, TCTG.
Updated URLs: DonTor, NNM, TCTG.
Removed Sites: baconBits, Milkie.

### CODE REVIEW

**Comment by neoOpus** [comment]
https://dontorrent.wtf/assets/DonFav.ico

**Comment by Purfview** [comment]
Issues:

1. Don't change version in PR.
2. Bring back DonTor png icon, ico is too big.
3. Don't comment out "removed" sites [baconbits], just remove them.
4. Uncomment Milkie, it's not dead.

**Comment by Purfview** [comment]
invalid

**Comment by neoOpus** [comment]
> Issues:
> 
> 1. Don't change version in PR.
> 2. Bring back DonTor png icon, ico is too big.
> 3. Don't comment out "removed" sites [baconbits], just remove them.
> 4. Uncomment Milkie, it's not dead.
> 5. No need to add anything to version log.

1- OK I will keep but what is PR?
2- The PNG isn't showing on my side! even if when I follow the link it is there! (I don't understand the reason)
3- I left them commented so you can decide to keep them or not... but next time I will take care to remove that
4- When I visited the website during the weekend it was down thus why I thought it has gone out of service.
5- So I guess you will take care of that yourself?!

**Comment by Purfview** [comment]
Please do. This PR changes I already added manually.

1. PR - "Pull request"
2. I'll move it to the script.
3. PRs are not a message system, post in issues.
5. Yes.

**Comment by neoOpus** [comment]
Error 403 for DonTor favicon image

**Comment by neoOpus** [comment]
> Check if this icon works:
> 
> https://dontorrent.wtf/assets/images/touch-icon.png

Yes seems to work

**Comment by neoOpus** [comment]
Still problematic... 

image

**Comment by Purfview** [comment]
Moved that icon to the script [v17.1].

**Pull request closed without merging**
