### PR TITLE
Added TNTC

### PR DESCRIPTION
**Pull request by mastercho**

### CODE REVIEW

**Comment by Purfview** [comment]
The sites for the pedophiles won't be added to this script.

**Comment by mastercho** [comment]
Didn't know that, found in reddit and was having turkish,russian movies which most sites missing

**Comment by Purfview** [comment]
> Didn't know that, found in reddit and was having turkish,russian movies which most sites missing

Oh yeah, can you share that link on reddit promoting this pedo site?

**Comment by mastercho** [comment]
https://www.reddit.com/r/warezbb/comments/jdrp9s/warezbb_dead/ Its was in comments here but seems is deleted as cant be found anymore, was in my bookmarks for long (to add in IMDB Scout)...

**Pull request closed without merging**
