### PR TITLE
Added Snahp

### PR DESCRIPTION
**Pull request by Xazmah**

### CODE REVIEW

**Comment by Purfview** [comment]
Snahp is already in script.

**Comment by Xazmah** [comment]
This is the blog site not the forum

**Comment by Purfview** [comment]
Then use forum. Links on that blog tries to install some malware.

**Comment by Xazmah** [comment]
You won't get any malware using uBlock or any other adblocker

**Comment by Xazmah** [comment]
@Purfview I really want this to be added, can you re-check if the malware issue is still present in the website?

**Comment by Purfview** [comment]
Didn't got malware now, but links doesn't work there as they are hidden behind 101 ads labyrinth.

I'm not adding any such anti-user site, period!
There is plenty of good DLL sites.

**Pull request closed without merging**
